// src/app/components/footer/footer.component.ts
import {Component} from '@angular/core';

interface FooterInfo {
  title: string,
  texts: string[]
}

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent {
  footerInfoData: FooterInfo[] = [
    {
      title: 'Navigation',
      texts: [
        'Home',
        'FAQ',
        'Investor Relations',
        'Jobs',
        'About Us',
        'Help Centre'
      ]
    },
    {
      title: 'legal',
      texts: [
        'Privacy Policy',
        'Terms of Service',
        'Cookie Preferences',
        'Corporate Information'
      ]
    },
    {
      title: 'talk to us',
      texts: [
        'support@ercom.com',
        '+66 2399 1145'
      ]
    },
    {
      title: 'follow us',
      texts: [
        'Facebook%20Icon.png',
        'Linkedin%20Icon.png',
        'Twitter%20Icon.png'
      ]
    }
  ];
}

<footer class="center">
  <div class="container center center-y">
    <div>
      <div class="footer-content">
        <button class="button center-y cursor-pointer">
          <img src="assets/icons/footer/globe%201.png" alt="globe"/>
          <p class="button-text">English</p>
          <img src="assets/icons/footer/Vector.png" alt="vector"/>
        </button>
        <div *ngFor="let footerInfo of footerInfoData | slice:0:3">
          <a routerLink="/" class="text-decoration-none">
            <p class="footer-info-title">{{footerInfo.title}}</p>
          </a>
          <a routerLink="/" class="text-decoration-none">
            <p class="footer-info-text" *ngFor="let text of footerInfo.texts">{{text}}</p>
          </a>
        </div>
        <div>
          <a routerLink="/" class="text-decoration-none">
            <p class="footer-info-title">{{footerInfoData[3].title}}</p>
          </a>
          <div class="footer-info-icons">
            <a routerLink="/" *ngFor="let icon of footerInfoData[3].texts">
              <img
                class="cursor-pointer"
                src="{{'assets/icons/footer/' + icon}}"
                alt="{{icon}}"
              />
            </a>
          </div>
        </div>
      </div>
      <p class="footer-text">© 2022 Dramatic. All Rights Reserved.</p>
    </div>
  </div>
</footer>

// src/components/Footer.jsx
function Footer() {
  return (
    <div className="w-100 text-left  text-white z-10 tracking-normal">
      <div className="flex justify-around w-full h-full box-border  py-28">
        <div className="languages">
          <div className="flex items-center justify-around  opacity-80">
            <img src="/assets/globe.svg" alt="" />
            <span>English</span>
          </div>
        </div>
        <div className="flex flex-col">
          <h5 className="font-bold font-proxima ">NAVIGATION</h5>
          <a className="font-roboto opacity-80 pt-2" href="/">
            Home
          </a>
          <a className="font-roboto opacity-80" href="/">
            FAQ
          </a>
          <a className="font-roboto opacity-80" href="/">
            Investor Relations
          </a>
          <a className="font-roboto opacity-80" href="/">
            Jobs
          </a>
          <a className="font-roboto opacity-80" href="/">
            About Us
          </a>
          <a className="font-roboto opacity-80" href="/">
            Help center
          </a>
        </div>
        <div className="flex flex-col">
          <h5 className="font-bold font-proxima ">LEGAL</h5>
          <a className="font-roboto opacity-80 pt-2" href="/">
            Privacy Policy
          </a>
          <a className="font-roboto opacity-80" href="/">
            Terms of service
          </a>
          <a className="font-roboto opacity-80" href="/">
            Cookie Preferences
          </a>
          <a className="font-roboto opacity-80" href="/">
            Corporate information
          </a>
        </div>
        <div className="flex flex-col">
          <h5 className="font-bold font">TALK TO US</h5>
          <p className="font-roboto opacity-80 pt-2">support@ercom.com</p>
          <p className="font-roboto opacity-80 ">+66 2399 1145</p>
        </div>
        <div className="flex flex-col">
          <h5 className="font-bold font">FOLLOW US</h5>
          <div className="flex py-3">
            <a href="/">
              <img src="/assets/facebook.svg" alt="" />
            </a>
            <a href="/">
              <img src="/assets/linkedin.svg" alt="" />
            </a>
            <a href="/">
              <img src="/assets/twitter.svg" alt="" />
            </a>
          </div>
        </div>
      </div>
      <p className="text-center">© 2022 Dramatic. All Rights Reserved. </p>
    </div>
  );
}

export default Footer;
