// src/app/components/footer/footer.component.ts
import {Component} from '@angular/core';

interface FooterInfo {
  title: string,
  texts: string[]
}

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent {
  footerInfoData: FooterInfo[] = [
    {
      title: 'Navigation',
      texts: [
        'Home',
        'FAQ',
        'Investor Relations',
        'Jobs',
        'About Us',
        'Help Centre'
      ]
    },
    {
      title: 'legal',
      texts: [
        'Privacy Policy',
        'Terms of Service',
        'Cookie Preferences',
        'Corporate Information'
      ]
    },
    {
      title: 'talk to us',
      texts: [
        'support@ercom.com',
        '+66 2399 1145'
      ]
    },
    {
      title: 'follow us',
      texts: [
        'Facebook%20Icon.png',
        'Linkedin%20Icon.png',
        'Twitter%20Icon.png'
      ]
    }
  ];
}

<footer class="center">
  <div class="container center center-y">
    <div>
      <div class="footer-content">
        <button class="button center-y cursor-pointer">
          <img src="assets/icons/footer/globe%201.png" alt="globe"/>
          <p class="button-text">English</p>
          <img src="assets/icons/footer/Vector.png" alt="vector"/>
        </button>
        <div *ngFor="let footerInfo of footerInfoData | slice:0:3">
          <a routerLink="/" class="text-decoration-none">
            <p class="footer-info-title">{{footerInfo.title}}</p>
          </a>
          <a routerLink="/" class="text-decoration-none">
            <p class="footer-info-text" *ngFor="let text of footerInfo.texts">{{text}}</p>
          </a>
        </div>
        <div>
          <a routerLink="/" class="text-decoration-none">
            <p class="footer-info-title">{{footerInfoData[3].title}}</p>
          </a>
          <div class="footer-info-icons">
            <a routerLink="/" *ngFor="let icon of footerInfoData[3].texts">
              <img
                class="cursor-pointer"
                src="{{'assets/icons/footer/' + icon}}"
                alt="{{icon}}"
              />
            </a>
          </div>
        </div>
      </div>
      <p class="footer-text">© 2022 Dramatic. All Rights Reserved.</p>
    </div>
  </div>
</footer>

// src/common/footer.jsx
import globe from '../assets/icons/Vector';
import vector from '../assets/icons/Vectorr';
import facebook from '../assets/icons/Facebook';
import linkedin from '../assets/icons/Linkedin';
import twitter from '../assets/icons/Twitter';


function Footer() {
    return (
        <div className="footer">
            <div className='links'>
                <div className="languages">
                    <div className="drop-box">
                        <img src={globe} alt="" />
                        <span>English</span>
                        <img src={vector} alt="" />
                    </div>
                </div>
                <div className="links-items">
                    <h5>NAVIGATION</h5>
                    <a href="#">Home</a>
                    <a href="#">FAQ</a>
                    <a href="#">Investor Relations</a>
                    <a href="#">Jobs</a>
                    <a href="#">About Us</a>
                    <a href="#">Help center</a>
                </div>
                <div className="links-items">
                    <h5>LEGAL</h5>
                    <a href="#">Privacy Policy</a>
                    <a href="#">Trems of service</a>
                    <a href="#">Cookie Preferences</a>
                    <a href="#">Corporate information</a>
                </div>
                <div className="links-items">
                    <h5>TALK TO US</h5>
                    <p>support@ercom.com</p>
                    <p>+66 2399 1145</p>
                </div>
                <div className="links-items">
                    <h5>FOLLOW US</h5>
                    <div>
                        <a href="#"><img src={facebook} alt="" /></a>
                        <a href="#"><img src={linkedin} alt="" /></a>
                        <a href="#"><img src={twitter} alt="" /></a>
                    </div>
                </div>
            </div>
            <p>© 2022 Dramatic. All Rights Reserved. </p>
        </div>
    );
}

export default Footer;
